name: Pytest

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch (adjust if necessary)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch (adjust if necessary)

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest version of Ubuntu

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover tests
